name: anolisos_8.9-x86_64
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/anolisos_8.9-x86_64.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull openanolis/anolisos:8.9-x86_64
          docker tag  openanolis/anolisos:8.9-x86_64 registry-intl.cn-hangzhou.aliyuncs.com/fky357/anolisos:8.9-x86_64
          docker push registry-intl.cn-hangzhou.aliyuncs.com/fky357/anolisos:8.9-x86_64
