name: filebrowser_latest
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/filebrowser_latest.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull filebrowser/filebrowser:latest
          docker tag  filebrowser/filebrowser:latest registry-intl.cn-hangzhou.aliyuncs.com/fky357/filebrowser:latest
          docker push registry-intl.cn-hangzhou.aliyuncs.com/fky357/filebrowser:latest
