name: strix-sandbox_0.1.10
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/strix-sandbox_0.1.10.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull ghcr.io/usestrix/strix-sandbox:0.1.10
          docker tag  ghcr.io/usestrix/strix-sandbox:0.1.10 registry-intl.cn-hangzhou.aliyuncs.com/fky357/strix-sandbox:0.1.10
          docker push registry-intl.cn-hangzhou.aliyuncs.com/fky357/strix-sandbox:0.1.10
